/////////////////////////////////////////////////////////////////
//                                                             //
// This Verilog file has been generated by the tool named Baya,//
// a tool from  EDAUtils                      //
// Contact help@edautils.com for support-info.   //
//                                                             //
//                                                             //
/////////////////////////////////////////////////////////////////
//
//
// Generated by : baya on 04/04/22, 2:28 AM
//
//


module clk_div(
        cdrst,
        clkin,
        clkout
    );
    parameter divider  = 16;
    input cdrst;
    input clkin;
    output clkout;
    localparam count_width  = CLogB2(divider);
    localparam zero  = { count_width { 1'b0 } } ;
    localparam one  = { { ( count_width - 1 ) { 1'b0 } } , { 1'b1 } };
    reg [( count_width - 1 ):0] count;
    wire [( count_width - 1 ):0] next_count;
    function  CLogB2;
        input [31:0] Number;
        integer i;
        begin
            i = Number;
            for ( CLogB2 = 0 ; ( i > 0 ) ; CLogB2 = ( CLogB2 + 1 ) )
            begin
                i = ( i >> 1 );
            end
        end
    endfunction 
endmodule 
