/////////////////////////////////////////////////////////////////
//                                                             //
// This Verilog file has been generated by the tool named Baya,//
// a tool from  EDAUtils                      //
// Contact help@edautils.com for support-info.   //
//                                                             //
//                                                             //
/////////////////////////////////////////////////////////////////
//
//
// Generated by : baya on 04/04/22, 2:28 AM
//
//


module debounce(
        reset,
        clk,
        noisy,
        clean
    );
    parameter ndelay  = 650000;
    input reset;
    input clk;
    input noisy;
    output reg  clean;
    localparam nbits  = CLogB2(ndelay);
    reg [( nbits - 1 ):0] count;
    reg  xnew;
    function  CLogB2;
        input [31:0] Number;
        integer i;
        begin
            i = Number;
            for ( CLogB2 = 0 ; ( i > 0 ) ; CLogB2 = ( CLogB2 + 1 ) )
            begin
                i = ( i >> 1 );
            end
        end
    endfunction 
endmodule 
