/////////////////////////////////////////////////////////////////
//                                                             //
// This Verilog file has been generated by the tool named Baya,//
// a tool from  EDAUtils                      //
// Contact help@edautils.com for support-info.   //
//                                                             //
//                                                             //
/////////////////////////////////////////////////////////////////
//
//
// Generated by : baya on 04/04/22, 2:28 AM
//
//


module hex2led(
        hex,
        led
    );
    parameter zero  =  ~( 8'b00111111);
    parameter one  =  ~( 8'b00000110);
    parameter two  =  ~( 8'b01011011);
    parameter three  =  ~( 8'b01001111);
    parameter four  =  ~( 8'b01100110);
    parameter five  =  ~( 8'b01101101);
    parameter six  =  ~( 8'b01111101);
    parameter seven  =  ~( 8'b00000111);
    parameter eight  =  ~( 8'b01111111);
    parameter nine  =  ~( 8'b01100111);
    input [3:0] hex;
    output reg [7:0] led;
endmodule 
