/////////////////////////////////////////////////////////////////
//                                                             //
// This Verilog file has been generated by the tool named Baya,//
// a tool from  EDAUtils                      //
// Contact help@edautils.com for support-info.   //
//                                                             //
//                                                             //
/////////////////////////////////////////////////////////////////
//
//
// Generated by : baya on 04/04/22, 2:28 AM
//
//


module upcounter(
        clk,
        enb,
        clr,
        count,
        max
    );
    parameter max_count  = 60;
    localparam bits  = CLogB2(max_count);
    localparam zero  = { bits { 1'b0 } } ;
    localparam one  = { { ( bits - 1 ) { 1'b0 } } , { 1'b1 } };


    input clk;
    input enb;
    input clr;
    output [( bits - 1 ):0] count;
    output max;
    reg [( bits - 1 ):0] counter;
    reg  saturate;
    wire [( bits - 1 ):0] next_counter;
    function  CLogB2;
        input [31:0] Number;
        integer i;
        begin
            i = Number;
            for ( CLogB2 = 0 ; ( i > 0 ) ; CLogB2 = ( CLogB2 + 1 ) )
            begin
                i = ( i >> 1 );
            end
        end
    endfunction 
endmodule 
