/////////////////////////////////////////////////////////////////
//                                                             //
// This Verilog file has been generated by the tool named Baya,//
// a tool from  EDAUtils                      //
// Contact help@edautils.com for support-info.   //
//                                                             //
//                                                             //
/////////////////////////////////////////////////////////////////
//
//
// Generated by : baya on 04/04/22, 2:28 AM
//
//


module watch_machine(
        clk,
        reset,
        strtstop,
        clken,
        rst
    );
    input clk;
    input reset;
    input strtstop;
    output reg  clken;
    output reg  rst;
    localparam clear  = 3'b000;
    localparam zero  = 3'b001;
    localparam start  = 3'b010;
    localparam counting  = 3'b011;
    localparam stop  = 3'b100;
    localparam stopped  = 3'b101;
    reg [2:0] current_state;
    reg [2:0] next_state;
endmodule 
